# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e823d66856a771b9da5fd81e7bedcdedf557f9002b106a35b880363c8a9c5224c2fe62aeebf0cae316856ef1932e7090c928cf7c5083d8e20dfd8c6918097e2

test:
  secret_key_base: 0c93f566573e02a5f4835d8059ea6f8813baf6a4ba631b1d6f27e8e7f03720f1f8236c174346595f8efde006f0411e9e7443e05f2c58157588c986e5ad84047f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
